DROP TABLE IF EXISTS products_images;
DROP TABLE IF EXISTS user_cart;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS users_auth;
DROP TABLE IF EXISTS users;

CREATE TABLE "users" (
  "id" serial PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "first_name" varchar(100),
  "last_name" varchar(100)
);

CREATE TABLE "users_auth" (
  "id" serial PRIMARY KEY,
  "user_id" int UNIQUE REFERENCES users(id),
  "hash" text
);

CREATE TABLE "products" (
  "id" serial PRIMARY KEY,
  "name" varchar(100),
  "description" varchar(300),
  "price" int
);

CREATE TABLE "products_images" (
  "id" serial PRIMARY KEY,
  "product_id" int REFERENCES products(id),
  "url" text
);

CREATE TABLE "user_cart" (
  "id" serial PRIMARY KEY,
  "user_id" int REFERENCES users(id),
  "product_id" int REFERENCES products(id),
  "quantity" int
);

insert into users(email, first_name, last_name) values('andrew@email.com', 'Andrew', 'Westenskow');

insert into products (name, description, price) values ('Wine - Pinot Noir Stoneleigh', 'Adaptive demand-driven productivity', 8930);
insert into products (name, description, price) values ('Flour - Teff', 'Cloned exuding open system', 828);
insert into products (name, description, price) values ('Doilies - 5, Paper', 'Progressive global instruction set', 9538);
insert into products (name, description, price) values ('Cinnamon Buns Sticky', 'Implemented attitude-oriented strategy', 2139);
insert into products (name, description, price) values ('Yucca', 'Compatible multi-state analyzer', 3005);
insert into products (name, description, price) values ('Wine - Gewurztraminer Pierre', 'Quality-focused system-worthy projection', 8106);
insert into products (name, description, price) values ('Pastry - French Mini Assorted', 'Digitized leading edge success', 9730);
insert into products (name, description, price) values ('Onions - Cooking', 'Optimized non-volatile application', 5720);
insert into products (name, description, price) values ('Fondant - Icing', 'Fully-configurable zero tolerance adapter', 6066);
insert into products (name, description, price) values ('Chick Peas - Canned', 'Multi-lateral attitude-oriented array', 9618);
insert into products (name, description, price) values ('Butter - Pod', 'Balanced static benchmark', 3464);
insert into products (name, description, price) values ('Fennel', 'Enterprise-wide secondary definition', 7749);
insert into products (name, description, price) values ('Sauce - Demi Glace', 'Realigned analyzing methodology', 4360);
insert into products (name, description, price) values ('Cream - 10%', 'Upgradable coherent architecture', 3242);
insert into products (name, description, price) values ('Tomatoes - Cherry', 'Triple-buffered value-added attitude', 6833);
insert into products (name, description, price) values ('Bread Cranberry Foccacia', 'Triple-buffered demand-driven local area network', 8409);
insert into products (name, description, price) values ('Cheese - Provolone', 'Realigned client-server matrices', 4987);
insert into products (name, description, price) values ('Banana - Leaves', 'Stand-alone background concept', 8339);
insert into products (name, description, price) values ('Lettuce - Lambs Mash', 'Sharable real-time local area network', 9805);
insert into products (name, description, price) values ('Nectarines', 'Versatile zero administration support', 1863);
insert into products (name, description, price) values ('Wine - Dubouef Macon - Villages', 'Multi-layered composite Graphic Interface', 8470);
insert into products (name, description, price) values ('Banana Turning', 'Profound eco-centric project', 429);
insert into products (name, description, price) values ('Swiss Chard', 'Exclusive eco-centric implementation', 3716);
insert into products (name, description, price) values ('Goat - Leg', 'Organized zero tolerance challenge', 8601);
insert into products (name, description, price) values ('Vodka - Lemon, Absolut', 'Down-sized eco-centric customer loyalty', 3239);
insert into products (name, description, price) values ('Pizza Pizza Dough', 'Operative logistical instruction set', 5533);
insert into products (name, description, price) values ('Pancetta', 'Organic static monitoring', 1374);
insert into products (name, description, price) values ('Sauce - Alfredo', 'Innovative attitude-oriented definition', 440);
insert into products (name, description, price) values ('Wine - White, Schroder And Schyl', 'Expanded analyzing approach', 4138);
insert into products (name, description, price) values ('Extract - Raspberry', 'Phased well-modulated orchestration', 7476);
insert into products (name, description, price) values ('Food Colouring - Orange', 'Programmable didactic open architecture', 4959);
insert into products (name, description, price) values ('Roe - Lump Fish, Red', 'Advanced content-based encryption', 2746);
insert into products (name, description, price) values ('Muffin Hinge 117n', 'Team-oriented clear-thinking secured line', 5754);
insert into products (name, description, price) values ('Pastry - Apple Muffins - Mini', 'Realigned context-sensitive task-force', 7743);
insert into products (name, description, price) values ('Dasheen', 'Re-engineered contextually-based array', 4266);
insert into products (name, description, price) values ('Oil - Pumpkinseed', 'Optimized asynchronous standardization', 3419);
insert into products (name, description, price) values ('Flour - Semolina', 'Self-enabling contextually-based secured line', 3102);
insert into products (name, description, price) values ('Devonshire Cream', 'Profit-focused radical matrices', 6589);
insert into products (name, description, price) values ('Fruit Salad Deluxe', 'Progressive directional support', 3139);
insert into products (name, description, price) values ('Cake - Miini Cheesecake Cherry', 'Fundamental grid-enabled alliance', 3505);
insert into products (name, description, price) values ('Truffle Paste', 'Digitized didactic complexity', 6756);
insert into products (name, description, price) values ('Buffalo - Striploin', 'Secured needs-based projection', 9731);
insert into products (name, description, price) values ('Absolut Citron', 'Quality-focused client-server leverage', 2135);
insert into products (name, description, price) values ('Cod - Salted, Boneless', 'Assimilated mission-critical emulation', 7611);
insert into products (name, description, price) values ('Wakami Seaweed', 'Multi-lateral client-driven website', 7652);
insert into products (name, description, price) values ('Ketchup - Tomato', 'Inverse bandwidth-monitored service-desk', 7181);
insert into products (name, description, price) values ('Flour - Corn, Fine', 'Advanced empowering matrix', 6944);
insert into products (name, description, price) values ('Ecolab - Hobart Washarm End Cap', 'Profit-focused directional interface', 6237);
insert into products (name, description, price) values ('Nori Sea Weed', 'Synergistic modular solution', 1293);
insert into products (name, description, price) values ('Wine - Mas Chicet Rose, Vintage', 'Assimilated 6th generation knowledge base', 9729);
insert into products (name, description, price) values ('Bok Choy - Baby', 'User-friendly demand-driven attitude', 8802);
insert into products (name, description, price) values ('Wine - Barolo Fontanafredda', 'Distributed actuating extranet', 9685);
insert into products (name, description, price) values ('Apples - Sliced / Wedge', 'Distributed 3rd generation utilisation', 7399);
insert into products (name, description, price) values ('Chocolate - Sugar Free Semi Choc', 'Mandatory responsive open architecture', 7347);
insert into products (name, description, price) values ('Spice - Onion Powder Granulated', 'Polarised 4th generation approach', 4626);
insert into products (name, description, price) values ('Sponge Cake Mix - Chocolate', 'Decentralized grid-enabled task-force', 9747);
insert into products (name, description, price) values ('Orange Roughy 4/6 Oz', 'Cross-group didactic flexibility', 7025);
insert into products (name, description, price) values ('Napkin - Dinner, White', 'Triple-buffered 24/7 hardware', 9103);

insert into products_images (product_id, url) values (26, 'http://dummyimage.com/133x209.bmp/cc0000/ffffff');
insert into products_images (product_id, url) values (31, 'http://dummyimage.com/165x184.bmp/ff4444/ffffff');
insert into products_images (product_id, url) values (16, 'http://dummyimage.com/107x127.png/ff4444/ffffff');
insert into products_images (product_id, url) values (48, 'http://dummyimage.com/141x103.jpg/cc0000/ffffff');
insert into products_images (product_id, url) values (19, 'http://dummyimage.com/228x126.bmp/5fa2dd/ffffff');
insert into products_images (product_id, url) values (10, 'http://dummyimage.com/110x169.png/ff4444/ffffff');
insert into products_images (product_id, url) values (13, 'http://dummyimage.com/135x226.bmp/5fa2dd/ffffff');
insert into products_images (product_id, url) values (1, 'http://dummyimage.com/227x234.png/5fa2dd/ffffff');
insert into products_images (product_id, url) values (15, 'http://dummyimage.com/209x164.png/cc0000/ffffff');
insert into products_images (product_id, url) values (48, 'http://dummyimage.com/213x150.bmp/cc0000/ffffff');
insert into products_images (product_id, url) values (15, 'http://dummyimage.com/163x132.jpg/cc0000/ffffff');
insert into products_images (product_id, url) values (7, 'http://dummyimage.com/146x131.bmp/ff4444/ffffff');
insert into products_images (product_id, url) values (47, 'http://dummyimage.com/215x196.bmp/cc0000/ffffff');
insert into products_images (product_id, url) values (58, 'http://dummyimage.com/210x112.png/ff4444/ffffff');
insert into products_images (product_id, url) values (35, 'http://dummyimage.com/152x199.jpg/ff4444/ffffff');
insert into products_images (product_id, url) values (45, 'http://dummyimage.com/191x157.png/ff4444/ffffff');
insert into products_images (product_id, url) values (23, 'http://dummyimage.com/108x122.jpg/dddddd/000000');
insert into products_images (product_id, url) values (42, 'http://dummyimage.com/142x162.png/ff4444/ffffff');
insert into products_images (product_id, url) values (45, 'http://dummyimage.com/218x221.bmp/ff4444/ffffff');
insert into products_images (product_id, url) values (32, 'http://dummyimage.com/243x180.png/cc0000/ffffff');
insert into products_images (product_id, url) values (48, 'http://dummyimage.com/117x236.bmp/5fa2dd/ffffff');
insert into products_images (product_id, url) values (33, 'http://dummyimage.com/116x230.png/dddddd/000000');
insert into products_images (product_id, url) values (39, 'http://dummyimage.com/143x117.jpg/ff4444/ffffff');
insert into products_images (product_id, url) values (38, 'http://dummyimage.com/128x201.png/cc0000/ffffff');
insert into products_images (product_id, url) values (16, 'http://dummyimage.com/182x232.png/cc0000/ffffff');
insert into products_images (product_id, url) values (33, 'http://dummyimage.com/142x177.png/cc0000/ffffff');
insert into products_images (product_id, url) values (8, 'http://dummyimage.com/130x146.bmp/dddddd/000000');
insert into products_images (product_id, url) values (17, 'http://dummyimage.com/143x145.bmp/dddddd/000000');
insert into products_images (product_id, url) values (51, 'http://dummyimage.com/203x146.png/ff4444/ffffff');
insert into products_images (product_id, url) values (55, 'http://dummyimage.com/103x167.png/cc0000/ffffff');
insert into products_images (product_id, url) values (37, 'http://dummyimage.com/123x118.jpg/dddddd/000000');
insert into products_images (product_id, url) values (47, 'http://dummyimage.com/129x146.png/5fa2dd/ffffff');
insert into products_images (product_id, url) values (21, 'http://dummyimage.com/167x138.jpg/ff4444/ffffff');
insert into products_images (product_id, url) values (4, 'http://dummyimage.com/173x168.jpg/cc0000/ffffff');
insert into products_images (product_id, url) values (37, 'http://dummyimage.com/146x210.bmp/cc0000/ffffff');
insert into products_images (product_id, url) values (4, 'http://dummyimage.com/149x113.png/dddddd/000000');
insert into products_images (product_id, url) values (50, 'http://dummyimage.com/208x149.bmp/dddddd/000000');
insert into products_images (product_id, url) values (31, 'http://dummyimage.com/229x113.bmp/cc0000/ffffff');
insert into products_images (product_id, url) values (23, 'http://dummyimage.com/233x112.jpg/5fa2dd/ffffff');
insert into products_images (product_id, url) values (55, 'http://dummyimage.com/213x111.jpg/ff4444/ffffff');
insert into products_images (product_id, url) values (39, 'http://dummyimage.com/165x113.png/5fa2dd/ffffff');
insert into products_images (product_id, url) values (32, 'http://dummyimage.com/202x250.bmp/dddddd/000000');
insert into products_images (product_id, url) values (12, 'http://dummyimage.com/172x188.jpg/dddddd/000000');
insert into products_images (product_id, url) values (30, 'http://dummyimage.com/180x169.bmp/cc0000/ffffff');
insert into products_images (product_id, url) values (56, 'http://dummyimage.com/237x100.jpg/cc0000/ffffff');
insert into products_images (product_id, url) values (51, 'http://dummyimage.com/162x209.bmp/dddddd/000000');
insert into products_images (product_id, url) values (55, 'http://dummyimage.com/219x127.jpg/ff4444/ffffff');
insert into products_images (product_id, url) values (51, 'http://dummyimage.com/160x218.bmp/5fa2dd/ffffff');
insert into products_images (product_id, url) values (3, 'http://dummyimage.com/239x167.png/ff4444/ffffff');
insert into products_images (product_id, url) values (43, 'http://dummyimage.com/217x105.bmp/5fa2dd/ffffff');
insert into products_images (product_id, url) values (24, 'http://dummyimage.com/171x147.jpg/5fa2dd/ffffff');
insert into products_images (product_id, url) values (16, 'http://dummyimage.com/149x194.jpg/cc0000/ffffff');
insert into products_images (product_id, url) values (31, 'http://dummyimage.com/209x117.png/5fa2dd/ffffff');
insert into products_images (product_id, url) values (57, 'http://dummyimage.com/229x221.bmp/ff4444/ffffff');
insert into products_images (product_id, url) values (57, 'http://dummyimage.com/186x244.jpg/cc0000/ffffff');
insert into products_images (product_id, url) values (5, 'http://dummyimage.com/102x140.jpg/5fa2dd/ffffff');
insert into products_images (product_id, url) values (48, 'http://dummyimage.com/122x119.png/5fa2dd/ffffff');
insert into products_images (product_id, url) values (55, 'http://dummyimage.com/161x224.jpg/ff4444/ffffff');
insert into products_images (product_id, url) values (19, 'http://dummyimage.com/208x164.jpg/cc0000/ffffff');
insert into products_images (product_id, url) values (42, 'http://dummyimage.com/106x176.jpg/cc0000/ffffff');
insert into products_images (product_id, url) values (47, 'http://dummyimage.com/230x118.png/cc0000/ffffff');
insert into products_images (product_id, url) values (48, 'http://dummyimage.com/126x122.bmp/dddddd/000000');
insert into products_images (product_id, url) values (6, 'http://dummyimage.com/156x141.jpg/dddddd/000000');
insert into products_images (product_id, url) values (49, 'http://dummyimage.com/191x113.jpg/5fa2dd/ffffff');
insert into products_images (product_id, url) values (7, 'http://dummyimage.com/144x235.png/cc0000/ffffff');
insert into products_images (product_id, url) values (34, 'http://dummyimage.com/158x205.png/5fa2dd/ffffff');
insert into products_images (product_id, url) values (43, 'http://dummyimage.com/120x210.png/cc0000/ffffff');
insert into products_images (product_id, url) values (38, 'http://dummyimage.com/228x236.bmp/ff4444/ffffff');
insert into products_images (product_id, url) values (13, 'http://dummyimage.com/246x127.png/dddddd/000000');
insert into products_images (product_id, url) values (15, 'http://dummyimage.com/202x191.png/ff4444/ffffff');
insert into products_images (product_id, url) values (41, 'http://dummyimage.com/206x201.bmp/cc0000/ffffff');
insert into products_images (product_id, url) values (25, 'http://dummyimage.com/158x230.jpg/dddddd/000000');
insert into products_images (product_id, url) values (16, 'http://dummyimage.com/203x198.jpg/cc0000/ffffff');
insert into products_images (product_id, url) values (17, 'http://dummyimage.com/108x153.png/ff4444/ffffff');
insert into products_images (product_id, url) values (16, 'http://dummyimage.com/128x106.jpg/cc0000/ffffff');
insert into products_images (product_id, url) values (34, 'http://dummyimage.com/247x219.bmp/ff4444/ffffff');
insert into products_images (product_id, url) values (41, 'http://dummyimage.com/236x158.png/cc0000/ffffff');
insert into products_images (product_id, url) values (39, 'http://dummyimage.com/222x108.bmp/cc0000/ffffff');
insert into products_images (product_id, url) values (24, 'http://dummyimage.com/219x139.bmp/ff4444/ffffff');
insert into products_images (product_id, url) values (54, 'http://dummyimage.com/222x187.jpg/5fa2dd/ffffff');
insert into products_images (product_id, url) values (4, 'http://dummyimage.com/157x185.png/ff4444/ffffff');
insert into products_images (product_id, url) values (36, 'http://dummyimage.com/126x221.png/cc0000/ffffff');
insert into products_images (product_id, url) values (56, 'http://dummyimage.com/112x186.bmp/cc0000/ffffff');
insert into products_images (product_id, url) values (42, 'http://dummyimage.com/130x167.bmp/5fa2dd/ffffff');
insert into products_images (product_id, url) values (32, 'http://dummyimage.com/250x237.bmp/cc0000/ffffff');
insert into products_images (product_id, url) values (16, 'http://dummyimage.com/148x114.png/ff4444/ffffff');
insert into products_images (product_id, url) values (13, 'http://dummyimage.com/106x191.bmp/dddddd/000000');
insert into products_images (product_id, url) values (22, 'http://dummyimage.com/116x175.bmp/ff4444/ffffff');
insert into products_images (product_id, url) values (5, 'http://dummyimage.com/180x236.jpg/cc0000/ffffff');
insert into products_images (product_id, url) values (42, 'http://dummyimage.com/143x177.png/dddddd/000000');
insert into products_images (product_id, url) values (44, 'http://dummyimage.com/217x168.png/5fa2dd/ffffff');
insert into products_images (product_id, url) values (2, 'http://dummyimage.com/228x186.jpg/dddddd/000000');
insert into products_images (product_id, url) values (5, 'http://dummyimage.com/188x121.png/ff4444/ffffff');
insert into products_images (product_id, url) values (22, 'http://dummyimage.com/241x138.jpg/ff4444/ffffff');
insert into products_images (product_id, url) values (28, 'http://dummyimage.com/131x182.png/cc0000/ffffff');
insert into products_images (product_id, url) values (5, 'http://dummyimage.com/223x153.png/cc0000/ffffff');
insert into products_images (product_id, url) values (39, 'http://dummyimage.com/172x140.png/5fa2dd/ffffff');
insert into products_images (product_id, url) values (53, 'http://dummyimage.com/148x223.bmp/dddddd/000000');
insert into products_images (product_id, url) values (38, 'http://dummyimage.com/212x116.jpg/dddddd/000000');
insert into products_images (product_id, url) values (50, 'http://dummyimage.com/104x235.png/cc0000/ffffff');
insert into products_images (product_id, url) values (53, 'http://dummyimage.com/137x216.png/dddddd/000000');
insert into products_images (product_id, url) values (23, 'http://dummyimage.com/234x133.bmp/dddddd/000000');
insert into products_images (product_id, url) values (35, 'http://dummyimage.com/245x153.jpg/ff4444/ffffff');
insert into products_images (product_id, url) values (51, 'http://dummyimage.com/192x131.bmp/dddddd/000000');
insert into products_images (product_id, url) values (24, 'http://dummyimage.com/241x144.png/cc0000/ffffff');
insert into products_images (product_id, url) values (26, 'http://dummyimage.com/100x250.bmp/5fa2dd/ffffff');
insert into products_images (product_id, url) values (55, 'http://dummyimage.com/229x149.bmp/cc0000/ffffff');
insert into products_images (product_id, url) values (27, 'http://dummyimage.com/249x241.bmp/dddddd/000000');
insert into products_images (product_id, url) values (30, 'http://dummyimage.com/186x213.png/ff4444/ffffff');
insert into products_images (product_id, url) values (53, 'http://dummyimage.com/110x183.jpg/dddddd/000000');
insert into products_images (product_id, url) values (39, 'http://dummyimage.com/115x177.bmp/ff4444/ffffff');
insert into products_images (product_id, url) values (21, 'http://dummyimage.com/113x161.png/cc0000/ffffff');
insert into products_images (product_id, url) values (30, 'http://dummyimage.com/173x213.png/ff4444/ffffff');
insert into products_images (product_id, url) values (44, 'http://dummyimage.com/166x210.bmp/cc0000/ffffff');
insert into products_images (product_id, url) values (29, 'http://dummyimage.com/180x143.png/cc0000/ffffff');
insert into products_images (product_id, url) values (26, 'http://dummyimage.com/189x142.png/ff4444/ffffff');
insert into products_images (product_id, url) values (2, 'http://dummyimage.com/172x240.jpg/cc0000/ffffff');
insert into products_images (product_id, url) values (28, 'http://dummyimage.com/208x110.png/dddddd/000000');
insert into products_images (product_id, url) values (52, 'http://dummyimage.com/104x221.bmp/dddddd/000000');
insert into products_images (product_id, url) values (49, 'http://dummyimage.com/112x121.bmp/ff4444/ffffff');
insert into products_images (product_id, url) values (4, 'http://dummyimage.com/110x161.jpg/ff4444/ffffff');
insert into products_images (product_id, url) values (15, 'http://dummyimage.com/162x206.bmp/ff4444/ffffff');
insert into products_images (product_id, url) values (27, 'http://dummyimage.com/111x222.bmp/ff4444/ffffff');
insert into products_images (product_id, url) values (48, 'http://dummyimage.com/242x228.png/dddddd/000000');
insert into products_images (product_id, url) values (16, 'http://dummyimage.com/200x206.bmp/cc0000/ffffff');
insert into products_images (product_id, url) values (37, 'http://dummyimage.com/157x211.png/5fa2dd/ffffff');
insert into products_images (product_id, url) values (22, 'http://dummyimage.com/170x107.png/dddddd/000000');
insert into products_images (product_id, url) values (20, 'http://dummyimage.com/134x225.png/dddddd/000000');
insert into products_images (product_id, url) values (5, 'http://dummyimage.com/129x170.bmp/ff4444/ffffff');
insert into products_images (product_id, url) values (35, 'http://dummyimage.com/166x102.jpg/cc0000/ffffff');
insert into products_images (product_id, url) values (20, 'http://dummyimage.com/130x144.jpg/cc0000/ffffff');
insert into products_images (product_id, url) values (38, 'http://dummyimage.com/240x221.jpg/5fa2dd/ffffff');
insert into products_images (product_id, url) values (39, 'http://dummyimage.com/189x105.png/ff4444/ffffff');
insert into products_images (product_id, url) values (28, 'http://dummyimage.com/218x161.jpg/5fa2dd/ffffff');
insert into products_images (product_id, url) values (52, 'http://dummyimage.com/120x120.jpg/ff4444/ffffff');
insert into products_images (product_id, url) values (47, 'http://dummyimage.com/119x150.bmp/dddddd/000000');
insert into products_images (product_id, url) values (2, 'http://dummyimage.com/160x188.jpg/cc0000/ffffff');
insert into products_images (product_id, url) values (39, 'http://dummyimage.com/110x236.bmp/dddddd/000000');
insert into products_images (product_id, url) values (22, 'http://dummyimage.com/168x113.bmp/5fa2dd/ffffff');
insert into products_images (product_id, url) values (17, 'http://dummyimage.com/247x138.png/cc0000/ffffff');
insert into products_images (product_id, url) values (42, 'http://dummyimage.com/160x221.jpg/ff4444/ffffff');
insert into products_images (product_id, url) values (2, 'http://dummyimage.com/126x233.bmp/cc0000/ffffff');
insert into products_images (product_id, url) values (18, 'http://dummyimage.com/194x168.png/cc0000/ffffff');
insert into products_images (product_id, url) values (19, 'http://dummyimage.com/243x186.bmp/cc0000/ffffff');
insert into products_images (product_id, url) values (24, 'http://dummyimage.com/137x170.bmp/ff4444/ffffff');
insert into products_images (product_id, url) values (53, 'http://dummyimage.com/110x102.jpg/dddddd/000000');
insert into products_images (product_id, url) values (32, 'http://dummyimage.com/220x131.bmp/cc0000/ffffff');
insert into products_images (product_id, url) values (3, 'http://dummyimage.com/126x157.jpg/dddddd/000000');
insert into products_images (product_id, url) values (4, 'http://dummyimage.com/159x183.bmp/5fa2dd/ffffff');
insert into products_images (product_id, url) values (50, 'http://dummyimage.com/244x245.bmp/dddddd/000000');
insert into products_images (product_id, url) values (34, 'http://dummyimage.com/164x137.jpg/cc0000/ffffff');
insert into products_images (product_id, url) values (22, 'http://dummyimage.com/118x221.png/ff4444/ffffff');
insert into products_images (product_id, url) values (40, 'http://dummyimage.com/126x118.png/cc0000/ffffff');
insert into products_images (product_id, url) values (17, 'http://dummyimage.com/172x156.bmp/dddddd/000000');
insert into products_images (product_id, url) values (9, 'http://dummyimage.com/154x153.bmp/dddddd/000000');
insert into products_images (product_id, url) values (24, 'http://dummyimage.com/205x192.png/cc0000/ffffff');
insert into products_images (product_id, url) values (16, 'http://dummyimage.com/114x160.jpg/dddddd/000000');
insert into products_images (product_id, url) values (48, 'http://dummyimage.com/100x232.bmp/cc0000/ffffff');
insert into products_images (product_id, url) values (42, 'http://dummyimage.com/249x122.png/5fa2dd/ffffff');
insert into products_images (product_id, url) values (49, 'http://dummyimage.com/128x187.bmp/ff4444/ffffff');
insert into products_images (product_id, url) values (11, 'http://dummyimage.com/234x242.png/dddddd/000000');
insert into products_images (product_id, url) values (2, 'http://dummyimage.com/170x219.bmp/cc0000/ffffff');
insert into products_images (product_id, url) values (33, 'http://dummyimage.com/119x130.jpg/cc0000/ffffff');
insert into products_images (product_id, url) values (27, 'http://dummyimage.com/210x183.png/dddddd/000000');
insert into products_images (product_id, url) values (53, 'http://dummyimage.com/140x159.bmp/5fa2dd/ffffff');
insert into products_images (product_id, url) values (58, 'http://dummyimage.com/112x197.png/cc0000/ffffff');
insert into products_images (product_id, url) values (2, 'http://dummyimage.com/146x229.bmp/dddddd/000000');
insert into products_images (product_id, url) values (14, 'http://dummyimage.com/170x156.bmp/dddddd/000000');
insert into products_images (product_id, url) values (55, 'http://dummyimage.com/181x163.bmp/5fa2dd/ffffff');
insert into products_images (product_id, url) values (25, 'http://dummyimage.com/191x134.jpg/ff4444/ffffff');
insert into products_images (product_id, url) values (49, 'http://dummyimage.com/211x216.bmp/5fa2dd/ffffff');
insert into products_images (product_id, url) values (38, 'http://dummyimage.com/183x204.png/cc0000/ffffff');
insert into products_images (product_id, url) values (27, 'http://dummyimage.com/160x184.png/dddddd/000000');
insert into products_images (product_id, url) values (6, 'http://dummyimage.com/198x168.jpg/cc0000/ffffff');
insert into products_images (product_id, url) values (29, 'http://dummyimage.com/204x142.jpg/cc0000/ffffff');
insert into products_images (product_id, url) values (52, 'http://dummyimage.com/216x100.png/ff4444/ffffff');
insert into products_images (product_id, url) values (46, 'http://dummyimage.com/108x216.bmp/5fa2dd/ffffff');
insert into products_images (product_id, url) values (21, 'http://dummyimage.com/185x200.png/cc0000/ffffff');
insert into products_images (product_id, url) values (25, 'http://dummyimage.com/213x191.jpg/ff4444/ffffff');
insert into products_images (product_id, url) values (18, 'http://dummyimage.com/242x126.jpg/cc0000/ffffff');
insert into products_images (product_id, url) values (26, 'http://dummyimage.com/125x171.jpg/dddddd/000000');
insert into products_images (product_id, url) values (9, 'http://dummyimage.com/159x178.jpg/ff4444/ffffff');
insert into products_images (product_id, url) values (27, 'http://dummyimage.com/204x244.png/cc0000/ffffff');
insert into products_images (product_id, url) values (25, 'http://dummyimage.com/249x100.jpg/dddddd/000000');
insert into products_images (product_id, url) values (33, 'http://dummyimage.com/240x211.jpg/ff4444/ffffff');
insert into products_images (product_id, url) values (5, 'http://dummyimage.com/225x210.jpg/ff4444/ffffff');
insert into products_images (product_id, url) values (10, 'http://dummyimage.com/216x166.bmp/cc0000/ffffff');
insert into products_images (product_id, url) values (6, 'http://dummyimage.com/185x198.png/5fa2dd/ffffff');
insert into products_images (product_id, url) values (31, 'http://dummyimage.com/170x121.png/ff4444/ffffff');
insert into products_images (product_id, url) values (37, 'http://dummyimage.com/242x195.bmp/ff4444/ffffff');
insert into products_images (product_id, url) values (18, 'http://dummyimage.com/168x234.png/cc0000/ffffff');
insert into products_images (product_id, url) values (3, 'http://dummyimage.com/137x135.bmp/5fa2dd/ffffff');
insert into products_images (product_id, url) values (57, 'http://dummyimage.com/108x209.jpg/ff4444/ffffff');
insert into products_images (product_id, url) values (16, 'http://dummyimage.com/165x229.png/5fa2dd/ffffff');
insert into products_images (product_id, url) values (40, 'http://dummyimage.com/158x210.png/5fa2dd/ffffff');
insert into products_images (product_id, url) values (25, 'http://dummyimage.com/112x108.bmp/dddddd/000000');
insert into products_images (product_id, url) values (33, 'http://dummyimage.com/133x109.bmp/ff4444/ffffff');
insert into products_images (product_id, url) values (44, 'http://dummyimage.com/192x248.png/dddddd/000000');
insert into products_images (product_id, url) values (8, 'http://dummyimage.com/153x164.jpg/cc0000/ffffff');
insert into products_images (product_id, url) values (50, 'http://dummyimage.com/143x103.jpg/ff4444/ffffff');
insert into products_images (product_id, url) values (46, 'http://dummyimage.com/191x202.png/cc0000/ffffff');
insert into products_images (product_id, url) values (5, 'http://dummyimage.com/203x208.bmp/dddddd/000000');
insert into products_images (product_id, url) values (42, 'http://dummyimage.com/247x114.png/ff4444/ffffff');
insert into products_images (product_id, url) values (50, 'http://dummyimage.com/161x109.png/cc0000/ffffff');
insert into products_images (product_id, url) values (20, 'http://dummyimage.com/145x142.bmp/dddddd/000000');
insert into products_images (product_id, url) values (28, 'http://dummyimage.com/156x199.bmp/dddddd/000000');
insert into products_images (product_id, url) values (14, 'http://dummyimage.com/152x235.bmp/5fa2dd/ffffff');
insert into products_images (product_id, url) values (35, 'http://dummyimage.com/119x102.bmp/5fa2dd/ffffff');
insert into products_images (product_id, url) values (19, 'http://dummyimage.com/165x114.jpg/5fa2dd/ffffff');
insert into products_images (product_id, url) values (47, 'http://dummyimage.com/249x142.bmp/cc0000/ffffff');
insert into products_images (product_id, url) values (18, 'http://dummyimage.com/185x188.png/cc0000/ffffff');
insert into products_images (product_id, url) values (56, 'http://dummyimage.com/110x126.jpg/dddddd/000000');
insert into products_images (product_id, url) values (36, 'http://dummyimage.com/194x127.bmp/5fa2dd/ffffff');
insert into products_images (product_id, url) values (25, 'http://dummyimage.com/134x226.png/cc0000/ffffff');
insert into products_images (product_id, url) values (47, 'http://dummyimage.com/196x228.png/5fa2dd/ffffff');
insert into products_images (product_id, url) values (7, 'http://dummyimage.com/129x167.jpg/ff4444/ffffff');
insert into products_images (product_id, url) values (50, 'http://dummyimage.com/149x107.jpg/5fa2dd/ffffff');
insert into products_images (product_id, url) values (19, 'http://dummyimage.com/203x126.png/cc0000/ffffff');
insert into products_images (product_id, url) values (38, 'http://dummyimage.com/219x206.bmp/dddddd/000000');
insert into products_images (product_id, url) values (14, 'http://dummyimage.com/120x184.bmp/5fa2dd/ffffff');
insert into products_images (product_id, url) values (9, 'http://dummyimage.com/173x196.png/cc0000/ffffff');
insert into products_images (product_id, url) values (16, 'http://dummyimage.com/191x121.bmp/5fa2dd/ffffff');
insert into products_images (product_id, url) values (17, 'http://dummyimage.com/110x143.bmp/cc0000/ffffff');
insert into products_images (product_id, url) values (22, 'http://dummyimage.com/186x242.jpg/cc0000/ffffff');
insert into products_images (product_id, url) values (11, 'http://dummyimage.com/115x141.png/cc0000/ffffff');
insert into products_images (product_id, url) values (33, 'http://dummyimage.com/203x126.jpg/ff4444/ffffff');
insert into products_images (product_id, url) values (56, 'http://dummyimage.com/146x160.jpg/ff4444/ffffff');
insert into products_images (product_id, url) values (3, 'http://dummyimage.com/121x250.bmp/cc0000/ffffff');
insert into products_images (product_id, url) values (23, 'http://dummyimage.com/224x206.jpg/dddddd/000000');
insert into products_images (product_id, url) values (11, 'http://dummyimage.com/103x228.jpg/ff4444/ffffff');
insert into products_images (product_id, url) values (55, 'http://dummyimage.com/165x102.jpg/dddddd/000000');
insert into products_images (product_id, url) values (40, 'http://dummyimage.com/167x147.jpg/5fa2dd/ffffff');
insert into products_images (product_id, url) values (46, 'http://dummyimage.com/249x244.bmp/dddddd/000000');
insert into products_images (product_id, url) values (6, 'http://dummyimage.com/209x131.jpg/ff4444/ffffff');
insert into products_images (product_id, url) values (47, 'http://dummyimage.com/153x233.bmp/cc0000/ffffff');
insert into products_images (product_id, url) values (58, 'http://dummyimage.com/235x148.png/5fa2dd/ffffff');
insert into products_images (product_id, url) values (41, 'http://dummyimage.com/136x218.png/ff4444/ffffff');
insert into products_images (product_id, url) values (35, 'http://dummyimage.com/161x170.bmp/cc0000/ffffff');
insert into products_images (product_id, url) values (32, 'http://dummyimage.com/246x216.png/ff4444/ffffff');
insert into products_images (product_id, url) values (40, 'http://dummyimage.com/122x118.png/ff4444/ffffff');
insert into products_images (product_id, url) values (43, 'http://dummyimage.com/175x157.jpg/5fa2dd/ffffff');
insert into products_images (product_id, url) values (55, 'http://dummyimage.com/208x246.bmp/5fa2dd/ffffff');
insert into products_images (product_id, url) values (34, 'http://dummyimage.com/132x212.bmp/dddddd/000000');
insert into products_images (product_id, url) values (6, 'http://dummyimage.com/171x205.bmp/5fa2dd/ffffff');
insert into products_images (product_id, url) values (38, 'http://dummyimage.com/161x201.png/5fa2dd/ffffff');
insert into products_images (product_id, url) values (11, 'http://dummyimage.com/105x139.png/5fa2dd/ffffff');
insert into products_images (product_id, url) values (19, 'http://dummyimage.com/180x183.png/dddddd/000000');
insert into products_images (product_id, url) values (29, 'http://dummyimage.com/244x101.jpg/dddddd/000000');
insert into products_images (product_id, url) values (41, 'http://dummyimage.com/194x208.jpg/dddddd/000000');
insert into products_images (product_id, url) values (40, 'http://dummyimage.com/223x179.bmp/dddddd/000000');
